### ISSUE TITLE
[QUESTION]what is changed in this book since i have started reading second edition. is it necessary to move to third edition 

### ISSUE THREAD

**Issue by kartikcpp** [ageron/handson-ml3#1]
Thanks for helping us improve this project!

**Before you create this issue**
Please make sure you are using the latest updated code and libraries: see https://github.com/ageron/handson-ml3/blob/main/INSTALL.md#update-this-project-and-its-libraries

Also please make sure to read the FAQ (https://github.com/ageron/handson-ml3#faq) and search for existing issues (both open and closed), as your question may already have been answered: https://github.com/ageron/handson-ml3/issues

**Describe what is unclear to you**
Please provide a clear and concise description of what the problem is, and specify the notebook name and the cell number at which the problem occurs (or the chapter and page in the book).

**To Reproduce**
If the question relates to a specific piece of code, please copy the code that fails here, using code blocks like this:

```python
def inverse(x):
    return 1 / x

result = inverse(0)
```

And if you get an exception, please copy the full stacktrace here:

```stacktrace
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in inverse
ZeroDivisionError: division by zero
```

**Expected behavior**
If applicable, a clear and concise description of what you expected to happen.

**Screenshots**

**Versions (please complete the following information):**
 - OS: [e.g. MacOSX 10.15.7]
 - Python: [e.g. 3.7]
 - TensorFlow: [e.g., 2.4.1]
 - Scikit-Learn: [e.g., 0.24.1]
- Other libraries that may be connected with the issue: [e.g., gym 0.18.0]

**Additional context**

**Comment by ageron** [comment]
Hi @kartikcpp ,

The second edition is fine, it's still mostly up to date, but the 3rd edition covers more topics and updates the code to the latest libraries. Here's a [list of improvements in the 3rd edition](https://twitter.com/aureliengeron/status/1494167572262301696?s=20&t=VNGnxuAAk8bjj0FvFY6AAw).

Hope this helps.

**Comment by rbague5** [comment]
Is in this third edition any chapter about deep learning Transformers models?

**Comment by ageron** [comment]
Yes, the chapter on NLP includes a presentation of Transformer models, how to build them, how to use the pretrained models from TF Hub, and a quick intro to HuggingFace's Transformers library and ecosystem.

**Comment by ageron** [comment]
The early release is already available on O'Reilly's Safari platform at https://homl.info/er3
It currently includes chapters 1 to 12, and more chapters will be added every few weeks.
I expect to finish writing the book within 6 to 8 weeks, but O'Reilly's production process takes quite a while because they review the text very thoroughly, they take care of page formatting, image resizing, creating the index, plus the final production process, and then there's the delivery time. So we're realistically looking at a release around October.

**Comment by TY-Cheng** [comment]
![image](https://user-images.githubusercontent.com/14033617/171545575-6af44fa2-295a-412c-af9f-e12bd1a96bca.png)
@ageron Hi ageron! Just a tiny comment that the repo description could shift to 3rd version as well. Thx!

**Comment by vi3itor** [comment]
@TY-Cheng, the description of the repo emphasizes that it covers TensorFlow 2. There is no information about the ongoing development of TensorFlow 3.0. The current "stable" version `2.9` [was released](https://github.com/tensorflow/tensorflow/releases) 16 days ago.

Unless you want Aurélien to rewrite the description to specifically mention the **3rd edition** of the book.

**Comment by atoshpulatov** [comment]
is there and discussion place where i can aks quesions and answers raised during reading the book ?

**Comment by ageron** [comment]
Hi @atoshpulatov ,
Yes, I'm happy to answer questions on github. Please:
1) start by searching in the [existing issues](https://github.com/ageron/handson-ml3/issues?q=is%3Aissue) (both opened and closed) whether your question has already been asked.
2) if not, please create a new issue and ask your question there, I'll do my best to answer it. 👍
