### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by alme7airbi93** [ageron/handson-ml3#5]
Thanks for helping us improve this project!

**Before you create this issue**
Please make sure you are using the latest updated code and libraries: see https://github.com/ageron/handson-ml3/blob/main/INSTALL.md#update-this-project-and-its-libraries

Also please make sure to read the FAQ (https://github.com/ageron/handson-ml3#faq) and search for existing issues (both open and closed), as your question may already have been answered: https://github.com/ageron/handson-ml3/issues

**Describe the bug**
Part 1 - Chapter 2 - (EndtoEndML), in creating `ColumnTransformer` supplying `feature_names_out` as argument  rises TypeError exception. 

**To Reproduce**
Please copy the code that fails here, using code blocks like this:

```
def ratio_pipeline(name=None):
    return make_pipeline(
        SimpleImputer(strategy="median"),
        FunctionTransformer(column_ratio, feature_names_out= lambda input_features: [name]),
        StandardScaler())
```

And if you got an exception, please copy the full stacktrace here:

```
Traceback (most recent call last):
  File "F:\*****\*****\*****\CHAPTER2-END_TO_END_PROJECT\final-example.py", line 49, in <module>
    ("bedrooms_ratio", ratio_pipeline("bedrooms_ratio"), ["total_bedrooms", "total_rooms"]),
  File "F:\*****\*****\*****\CHAPTER2-END_TO_END_PROJECT\final-example.py", line 38, in ratio_pipeline
    FunctionTransformer(column_ratio, feature_names_out= lambda input_features: [name]),
TypeError: FunctionTransformer.__init__() got an unexpected keyword argument 'feature_names_out'
```

**Expected behavior**
The preprocessing fit and transform the dataset 

**Versions (please complete the following information):**
 - OS: Windows 10
 - Python: 3.10
 - TensorFlow: ****
 - Scikit-Learn: 1.0.2
- Other libraries that may be connected with the issue:*****

**Additional context**

This is my full code 

```
import numpy as np
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.cluster import KMeans
from sklearn.compose import ColumnTransformer, make_column_selector
from sklearn.impute import SimpleImputer
from sklearn.metrics.pairwise import rbf_kernel
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import FunctionTransformer, StandardScaler, OneHotEncoder
from data import housing


class ClusterSimilarity(BaseEstimator, TransformerMixin):
    def __init__(self, n_clusters=10, gamma=1.0, random_state=None):
        self.n_clusters = n_clusters
        self.gamma = gamma
        self.random_state = random_state

    def fit(self, X, y=None, sample_weight=None):
        self.kmeans_ = KMeans(self.n_clusters, random_state=self.random_state)
        self.kmeans_.fit(X, sample_weight=sample_weight)
        return self  # always return self!

    def transform(self, X):
        return rbf_kernel(X, self.kmeans_.cluster_centers_, gamma=self.gamma)

    def get_feature_names_out(self, names=None):
        return [f"Cluster {i} similarity" for i in range(self.n_clusters)]


def column_ratio(X):
    return X[:, [0]] / X[:, [1]]


def ratio_pipeline(name=None):
    return make_pipeline(
        SimpleImputer(strategy="median"),
        FunctionTransformer(column_ratio, feature_names_out= lambda input_features: [name]),
        StandardScaler())


log_pipeline = make_pipeline(SimpleImputer(strategy="median"), FunctionTransformer(np.log), StandardScaler())
cluster_simil = ClusterSimilarity(n_clusters=10, gamma=1., random_state=42)
default_num_pipeline = make_pipeline(SimpleImputer(strategy="median"),StandardScaler())

cat_pipeline = make_pipeline(SimpleImputer(strategy="most_frequent"), OneHotEncoder(handle_unknown="ignore"))

preprocessing = ColumnTransformer([
    ("bedrooms_ratio", ratio_pipeline("bedrooms_ratio"), ["total_bedrooms", "total_rooms"]),
    ("rooms_per_house", ratio_pipeline("rooms_per_house"), ["total_rooms", "households"]),
    ("people_per_house", ratio_pipeline("people_per_house"), ["population", "households"]),
    ("log", log_pipeline, ["total_bedrooms", "total_rooms", "population", "households", "median_income"]),
    ("geo", cluster_simil, ["latitude", "longitude"]),
    ("cat", cat_pipeline, make_column_selector(dtype_include=np.object)),
], remainder=default_num_pipeline)  # one column remaining: housing_median_age


if __name__ == '__main__':
    housing_prepared = preprocessing.fit_transform(housing)
    print(housing_prepared.shape)
    print(preprocessing.get_feature_names_out())
```

**Comment by alme7airbi93** [comment]
I have tried to use python3.8 too still I get the same exception

**Comment by FriedrichFroebel** [comment]
`feature_names_out` is part of the upcoming v1.1 release of *sklearn* (see https://scikit-learn.org/dev/modules/generated/sklearn.preprocessing.FunctionTransformer.html and https://github.com/scikit-learn/scikit-learn/commit/d23d589587ce5a6d5642018946511ef3818bcb32) and not yet available if you use the latest official release.

**Comment by alme7airbi93** [comment]
Many thanks @FriedrichFroebel , After upgrading the sklearn I was able to run the code. 
However I encountered another error now. 

**Error rise in this line** 


```
print(preprocessing.get_feature_names_out())
```

**Exception**

```
Traceback (most recent call last):
  File "F:\****\Python Projects\ML-Book-Practice\CHAPTER2-END_TO_END_PROJECT\final-example.py", line 60, in <module>
    print(preprocessing.get_feature_names_out())
  File "F:\****\Python Projects\ML-Book-Practice\venv\lib\site-packages\sklearn\compose\_column_transformer.py", line 479, in get_feature_names_out
    feature_names_out = self._get_feature_name_out_for_transformer(
  File "F:\****\Python Projects\ML-Book-Practice\venv\lib\site-packages\sklearn\compose\_column_transformer.py", line 451, in _get_feature_name_out_for_transformer
    return trans.get_feature_names_out(names)
  File "F:\****\Python Projects\ML-Book-Practice\venv\lib\site-packages\sklearn\pipeline.py", line 733, in get_feature_names_out
    feature_names_out = transform.get_feature_names_out(feature_names_out)
  File "F:\****\Python Projects\ML-Book-Practice\venv\lib\site-packages\sklearn\utils\metaestimators.py", line 129, in <lambda>
    out = lambda *args, **kwargs: self.fn(obj, *args, **kwargs)  # noqa
  File "F:\****\Python Projects\ML-Book-Practice\venv\lib\site-packages\sklearn\preprocessing\_function_transformer.py", line 277, in get_feature_names_out
    names_out = self.feature_names_out(self, input_features)
TypeError: ratio_pipeline.<locals>.<lambda>() takes 1 positional argument but 2 were given
(20640, 25)

Process finished with exit code 1

```

**These are list of packages installed** 

![image](https://user-images.githubusercontent.com/14976829/163481236-2e186c5c-a649-44ca-a977-72cba00cfba8.png)

**Comment by ageron** [comment]
Hi @alme7airbi93 ,

Thanks for your feedback. The new feature name tracking in Scikit-Learn is great but it's not entirely finished (as of Scikit-Learn 1.0.2). Since I expect that it will be finished by the time the 3rd edition of my book is released, I chose to anticipate what's coming, and write the book as if everything already works. To ensure that everything works well, I have added the following function to the Colab notebook:

```python
def monkey_patch_get_signature_names_out():
    """Monkey patch some classes which did not handle get_feature_names_out()
       correctly in 1.0.0."""
    from inspect import Signature, signature, Parameter
    import pandas as pd
    from sklearn.impute import SimpleImputer
    from sklearn.pipeline import make_pipeline, Pipeline
    from sklearn.preprocessing import FunctionTransformer, StandardScaler

    default_get_feature_names_out = StandardScaler.get_feature_names_out

    if not hasattr(SimpleImputer, "get_feature_names_out"):
      print("Monkey-patching SimpleImputer.get_feature_names_out()")
      SimpleImputer.get_feature_names_out = default_get_feature_names_out

    if not hasattr(FunctionTransformer, "get_feature_names_out"):
        print("Monkey-patching FunctionTransformer.get_feature_names_out()")
        orig_init = FunctionTransformer.__init__
        orig_sig = signature(orig_init)

        def __init__(*args, feature_names_out=None, **kwargs):
            orig_sig.bind(*args, **kwargs)
            orig_init(*args, **kwargs)
            args[0].feature_names_out = feature_names_out

        __init__.__signature__ = Signature(
            list(signature(orig_init).parameters.values()) + [
                Parameter("feature_names_out", Parameter.KEYWORD_ONLY)])

        def get_feature_names_out(self, names=None):
            if self.feature_names_out is None:
                return default_get_feature_names_out(self, names)
            elif callable(self.feature_names_out):
                return self.feature_names_out(names)
            else:
                return self.feature_names_out

        FunctionTransformer.__init__ = __init__
        FunctionTransformer.get_feature_names_out = get_feature_names_out

monkey_patch_get_signature_names_out()
```

After you run this code, the code in the book should work fine.

**Note**: I believe this is the only place in the book where the code won't run without some tweaks. But if you do run into any other problem, please make sure to check out the notebook: it should contain working code.

Hope this helps!

**Comment by alme7airbi93** [comment]
Hi @ageron , Thanks a lot for the update.
